### ISSUE TITLE
warning: trailing semicolon in macro used in expression position

### ISSUE THREAD

**Issue by Christoph1111** [jamesmortensen/geckodriver-arm-binaries#1]
Thanks for helping me compiling, it works...

# cargo --version
cargo 1.59.0 (49d8809dc 2022-02-10)
# rustc --version
rustc 1.59.0 (9d1b2106e 2022-02-23)

warning: trailing semicolon in macro used in expression position
   --> src/main.rs:118:63
    |
118 |         return Err(FatalError::Usage(format!($fmt, $($arg)+)));
    |                                                               ^
...
154 |             Err(e) => usage!("invalid --port: {}: {}", e, s),
    |                       -------------------------------------- in this macro invocation
    |
    = note: `#[warn(semicolon_in_expressions_from_macros)]` on by default
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
    = note: this warning originates in the macro `usage` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: trailing semicolon in macro used in expression position
   --> src/main.rs:118:63
    |
118 |         return Err(FatalError::Usage(format!($fmt, $($arg)+)));
    |                                                               ^
...
159 |         Err(e) => usage!("{}: {}:{}", e, host, port),
    |                   ---------------------------------- in this macro invocation
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
    = note: this warning originates in the macro `usage` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: trailing semicolon in macro used in expression position
   --> src/main.rs:118:63
    |
118 |           return Err(FatalError::Usage(format!($fmt, $($arg)+)));
    |                                                                 ^
...
162 | /         usage!(
163 | |             "invalid --host: {}. Must be a local loopback interface",
164 | |             host
165 | |         )
    | |_________- in this macro invocation
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
    = note: macro invocations at the end of a block are treated as expressions
    = note: to ignore the value produced by the macro, add a semicolon after the invocation of `usage`
    = note: this warning originates in the macro `usage` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: trailing semicolon in macro used in expression position
   --> src/main.rs:118:63

    |
118 |         return Err(FatalError::Usage(format!($fmt, $($arg)+)));
    |                                                               ^
...
177 |             Err(e) => usage!("invalid --marionette-port: {}", e),
    |                       ------------------------------------------ in this macro invocation
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a fu
ture release!
    = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
    = note: this warning originates in the macro `usage` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: trailing semicolon in macro used in expression position
   --> src/main.rs:118:63
    |
118 |         return Err(FatalError::Usage(format!($fmt, $($arg)+)));
    |                                                               ^
...
187 |             Err(e) => usage!("invalid --websocket-port: {}", e),
    |                       ----------------------------------------- in this macro invocation
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
    = note: this warning originates in the macro `usage` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by jamesmortensen** [comment]
Hi @Christoph1111 Sorry, I am not able to understand.  Are you having trouble compiling and need help, or did you get it to work?

**Comment by Christoph1111** [comment]
Hi James,
No trouble, it compiled, thanks.
Just got this warnings and posted it. Maybe for the future...

Regards

**Comment by jamesmortensen** [comment]
Awesome.  This issue sounds more like an upstream issue, something [mozilla/geckodriver](https://github.com/mozilla/geckodriver) will need to handle, so I'll close it for now.  Also, you can find the compiled aarch64 binary on the [Releases page](https://github.com/jamesmortensen/geckodriver-arm-binaries/releases) if you want to avoid having to build it yourself.  Cheers!
